import Featured from "@/components/featured";
import Pizzalist from "@/components/pizzalist";
import Head from "next/head";
import axios from "axios";

export default function Home({ PizzaList }) {
  return (
    <>
      <Head>
        <title>Food Order App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <Pizzalist PizzaList={PizzaList} />
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get("http://localhost:3000/api/products");

  return {
    props: {
      PizzaList: res.data,
    },
  };
};
