import Featured from "@/components/featured";
import Pizzalist from "@/components/pizzalist";
import Head from "next/head";
import axios from "axios";
import Add from "@/components/Add";
import AddButton from "@/components/AddButton";
import { useState } from "react";
import { server } from "@/next.config";

export default function Home({ PizzaList }) {
  const [close, setClose] = useState(true);
  return (
    <>
      <Head>
        <title>Food Order App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Featured />
      <AddButton setClose={setClose} />
      <Pizzalist PizzaList={PizzaList} />
      {!close && <Add setClose={setClose} />}
    </>
  );
}

export const getServerSideProps = async () => {
  const res = await axios.get(`${process.env.BASE_URL}/api/products`);

  return {
    props: {
      PizzaList: res.data,
    },
  };
};
